// Code generated by "stringer --type=ExpenseCategory"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UNKNOWN_EXPENSE-0]
	_ = x[RENT-1]
	_ = x[HOME-2]
	_ = x[GROCERIES-3]
	_ = x[FOOD-4]
	_ = x[SPLIT-5]
	_ = x[TRAVEL-6]
	_ = x[LUXURY-7]
	_ = x[TELECOM-8]
	_ = x[OUTING-9]
}

const _ExpenseCategory_name = "UNKNOWN_EXPENSERENTHOMEGROCERIESFOODSPLITTRAVELLUXURYTELECOMOUTING"

var _ExpenseCategory_index = [...]uint8{0, 15, 19, 23, 32, 36, 41, 47, 53, 60, 66}

func (i ExpenseCategory) String() string {
	if i >= ExpenseCategory(len(_ExpenseCategory_index)-1) {
		return "ExpenseCategory(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExpenseCategory_name[_ExpenseCategory_index[i]:_ExpenseCategory_index[i+1]]
}
